name: CI

on:
  push:
    branches: [master]
  pull_request_target:
    branches: ['**']

permissions:
  contents: read

jobs:
  test:
    name: Run linter and tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - run: |
        git fetch origin "$REF"
        git checkout "$REF"
      env:
        REF: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Check if dist is updated
      run: |
        npm run build
        set -e # exit immediate if a command below returns a non-zero status
        git status # display the results for debugging
        test -z "$(git status --porcelain)"

    - name: Run linter and tests
      run: |
        npm run lint
        npm test
        npm run coverage

    - name: Send test coverage report to Coveralls
      uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
